version: "3"
services:
    mango:
        image: "mango:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: mango
        stdin_open: true
        tty: true
        working_dir: '/mango-dev'
        volumes:
            - ".:/mango-dev"
